# ***Fuzzy C-mean***

## **Pengertiann Fuzzy C-Means**

**Fuzzy C-Means** (FCM) adalah metode clustering (pengelompokan data) yang termasuk dalam kategori soft clustering. Berbeda dengan metode clustering tradisional seperti K-Means yang menempatkan setiap titik data ke dalam satu dan hanya satu cluster, FCM memungkinkan setiap titik data memiliki derajat keanggotaan pada cluster yang berbeda-beda. Derajat keanggotaan ini biasanya bernilai antara 0 dan 1, di mana nilai yang mendekati 1 menunjukkan tingkat keanggotaan yang tinggi pada cluster tersebut.

## **Langkah Langkah Algoritma Fuzzy C-Means**

Konsep dasar dari algortima ini menemukan nilai derajat keanggotaan dari semua data yang ada pada centroid/Nilai tengah, serta mencari titik centroid dari setiap cluster yang sudah ditentukan. Langkah ini bersifata iteratif(berulang) dengan langkah-langkah berikut:

1. Inisialisasi
    - Menentukan jumlah cluster yang akan digunakan
    - Menentukan nilai derajat anggota pada setiap centroid cluster. 
2. Menghitung Centroid:
    - Titik centroid sendiri diperoleh dari perhitungan nilai derajat anggota, nanti penulis sertakan rumusnya
3. Memperbarui Matriks Keanggotaan:
    - Setelah perhitungan centroid sudah dilakukan, maka perbarui nilai derajat keanggotaan pada setiap anggota dengan menggunakan hasil Centroid tadi. Nilai dari derajat keanggotaan yang semakin dekat, maka akan semakin tinggi nilainya. 
4. Evaluasi: 
    - Biasanya pengulangan perhitungan tersebut terus dilakukan sampai dengan batas iterasi yang ditentukan atau sampai dengan mencapai nilai error yang telah mencapai nilai minimum. Nilai error ini biasanay ditentukan dari perbandingan antar nilai derajat keanggotaan, atau nilai centroid dari suatu cluster serta bisa juga gabungan antara keduanya yaitu fungsi objektif. Langkah ini biasa disebut dengan perhitungan nilai konvergensi

## **Rumus Rumus Fuzzy-Cmeans**

### *Rumus Perhitungan Centroid*


Setelah matriks keanggotaan ($U$) diinisialisasi atau dihitung, pusat *cluster* ($v_i$) diperbarui menggunakan rumus berikut:

$$v_i = \frac{\sum_{k=1}^{n} (u_{ik})^m x_k}{\sum_{k=1}^{n} (u_{ik})^m}$$

Di mana:
* $v_i$: Pusat *cluster* ke-$i$.
* $n$: Jumlah total titik data.
* $u_{jk}$: Derajat keanggotaan titik data ke-$k$ terhadap klaster $j$.
* $m$: Parameter *fuzziness* (dalam kasus ini, $m=2$).
* $x_k$: Titik data ke-$k$.


* $\sum_{k=1}^{n} (\mu_{ik})^m x_k$: Penjumlahan dari setiap titik data $x_k$ yang dibobot oleh derajat keanggotaannya terhadap *cluster* $i$ yang dipangkatkan $m$.
* $\sum_{k=1}^{n} (\mu_{ik})^m$: Jumlah bobot keanggotaan dari semua titik data terhadap *cluster* $i$.



Rumus ini pada dasarnya menghitung rata-rata tertimbang (weighted average) dari semua titik data untuk menentukan posisi centroid, di mana bobotnya adalah derajat keanggotaan.

### *Rumus Perhitungan Nilai Derajat Keanggotaan*

Setelah pusat *cluster* ($V$) dihitung, matriks keanggotaan ($U$) diperbarui menggunakan rumus berikut:

$$\mu_{ik} = \frac{1}{\sum_{j=1}^{c} \left( \frac{\|x_k - v_i\|}{\|x_k - v_j\|} \right)^{\frac{2}{m-1}}}$$

Di mana:
* $\mu_{ik}$: Derajat keanggotaan titik data $x_k$ pada *cluster* $i$.
* $\|x_k - v_i\|$: Jarak Euclidean antara $x_k$ dan pusat *cluster* $v_i$.
* $\|x_k - v_j\|$: Jarak Euclidean antara $x_k$ dan pusat *cluster* $v_j$ (untuk setiap *cluster* $j$).

Rumus ini menunjukkan bahwa derajat keanggotaan titik data $x_k$ pada suatu *cluster* $i$ berbanding terbalik dengan jaraknya dari pusat *cluster* $v_i$, dan berbanding terbalik dengan jaraknya dari semua pusat *cluster* lainnya. Semakin dekat $x_k$ ke $v_i$, semakin tinggi $\mu_{ik}$.


### *Rumus Perhitungan Fungsi Objektif*

Fungsi objektif yang diminimalkan oleh FCM adalah:

$$J_m(U, V) = \sum_{k=1}^{n} \sum_{i=1}^{c} (\mu_{ik})^m \|x_k - v_i\|^2$$

Di mana:
* $J_m(U, V)$: Nilai fungsi objektif.
* $(\mu_{ik})^m$: Derajat keanggotaan $x_k$ pada *cluster* $i$ yang dipangkatkan dengan $m$. Ini memberikan bobot yang lebih besar pada titik data yang memiliki keanggotaan kuat pada suatu *cluster*.
* $\|x_k - v_i\|^2$: Kuadrat jarak Euclidean antara titik data $x_k$ dan pusat *cluster* $v_i$.

Tujuan algoritma ini adalah mencari $U$ dan $V$ yang meminimalkan $J_m$.


### *Contoh Perhitungan Manual*

1. **Proses Inisialisasi**

Penulis memiliki suatu contoh data yang akan dihitung dengan cara manual menggunakan rumus rumus yang sudah disampaikan pada materi di atas. berikut ini adalah contoh data datanya:

| No Data | x1 | x2 |
|----------|----------|----------|
| 1 | 1 | 2 |
| 2 | 2 | 3 |
| 3 | 3 | 4 |
| 4 | 6 | 7 |
| 5 | 7 | 8 |

Pertama kita harus tentukan dulu, kira kira berapa cluster yang ingin kita buat. Karena kita sudah mengetahui data datanya kita bisa menginisialisasi nilai derajat keanggotaannya secara acak agar nanti kita bisa mendapatkan nilai centroid dari setiap cluster. berikut ini adalah nilai derajat keanggotaanya yang penulis buat secara acak: 

| No Data | Nilai Ke C1 | Nilai Ke C2 |
|----------|----------|----------|
| 1 | 0,5 | 0,5 |
| 2 | 0,7 | 0,3 |
| 3 | 0,8 | 0,2 |
| 4 | 0,7 | 0,3 |
| 5 | 0,6 | 0,4 |



2. a.**Menghitung Centroid Cluster 1**

$$v_i = \frac{\sum_{k=1}^{n} (u_{ik})^m x_k}{\sum_{k=1}^{n} (u_{ik})^m}$$

Dengan menggunakan rumus yang telah penulis cantumkan dan juga pada materi diatas kita bisa menggunakannya untuk menghitung pusat cluster dari setiap cluter yang sudah ditentukan. Karena hanya sebagai contoh perhitungan, saya hanya menggunakan 2 cluster saja. Berikut ini adalah contoh perhitungannya

* Hitung Pembilang (Numerator): $\sum_{k=1}^{N} (u_{1k})^m \cdot x_k$

    Ini adalah perkalian element-wise antara $(u_{1k})^m$ dan $x_k$, kemudian dijumlahkan.
$$
\begin{aligned}
\text{Numerator} &= (u_{11}^2 \cdot x_1) + (u_{12}^2 \cdot x_2) + (u_{13}^2 \cdot x_3) + (u_{14}^2 \cdot x_4) + (u_{15}^2 \cdot x_5) \\
&= (0.25 \cdot \begin{bmatrix} 1 & 2 \end{bmatrix}) + (0.49 \cdot \begin{bmatrix} 2 & 3 \end{bmatrix}) + (0.64 \cdot \begin{bmatrix} 3 & 4 \end{bmatrix}) + (0.49 \cdot \begin{bmatrix} 6 & 7 \end{bmatrix}) + (0.36 \cdot \begin{bmatrix} 7 & 8 \end{bmatrix}) \\
&= \begin{bmatrix} 0.25 & 0.50 \end{bmatrix} + \begin{bmatrix} 0.98 & 1.47 \end{bmatrix} + \begin{bmatrix} 1.92 & 2.56 \end{bmatrix} + \begin{bmatrix} 2.94 & 3.43 \end{bmatrix} + \begin{bmatrix} 2.52 & 2.88 \end{bmatrix} \\
&= \begin{bmatrix} (0.25 + 0.98 + 1.92 + 2.94 + 2.52) & (0.50 + 1.47 + 2.56 + 3.43 + 2.88) \end{bmatrix} \\
&= \begin{bmatrix} 8.61 & 10.84 \end{bmatrix}
\end{aligned}
$$

* Hitung Penyebut (Denominator): $\sum_{k=1}^{N} (u_{1k})^m$

    Ini adalah penjumlahan semua nilai $(u_{1k})^m$.
$$
\begin{aligned}
\text{Denominator} &= u_{11}^2 + u_{12}^2 + u_{13}^2 + u_{14}^2 + u_{15}^2 \\
&= 0.25 + 0.49 + 0.64 + 0.49 + 0.36 \\
&= 2.23
\end{aligned}
$$


* Hitung Centroid Cluster 1 ($C_1$): $\begin{aligned}\frac{\text{Numerator}}{\text{Denominator}}\end{aligned}$

    Terakhir, bagi pembilang dengan penyebut.

$$
\begin{aligned}
&= \frac{\begin{bmatrix} 8.61 & 10.84 \end{bmatrix}}{2.23} \\
&= \begin{bmatrix} \frac{8.61}{2.23} & \frac{10.84}{2.23} \end{bmatrix} \\
&\approx \begin{bmatrix} 3.860986547 & 4.860986547 \end{bmatrix}
\end{aligned}
$$

* Hasil Akhir:

    Centroid Cluster 1 adalah $\begin{bmatrix} 3.861 & 4.861 \end{bmatrix}$ (dibulatkan hingga tiga angka desimal).



2. b.**Menghitung Centroid Cluster 2**

* Rumus Centroid :
$$v_i = \frac{\sum_{k=1}^{n} (u_{ik})^m x_k}{\sum_{k=1}^{n} (u_{ik})^m}$$


* Hitung Pembilang (Numerator): $\sum_{k=1}^{N} (u_{1k})^m \cdot x_k$

    Ini adalah perkalian element-wise antara $(u_{1k})^m$ dan $x_k$, kemudian dijumlahkan.
$$
\begin{aligned}
\text{Numerator} &= (u_{21}^2 \cdot x_1) + (u_{22}^2 \cdot x_2) + (u_{23}^2 \cdot x_3) + (u_{24}^2 \cdot x_4) + (u_{25}^2 \cdot x_5) \\
&= (0.25 \cdot \begin{bmatrix} 1 & 2 \end{bmatrix}) + (0.09 \cdot \begin{bmatrix} 2 & 3 \end{bmatrix}) + (0.04 \cdot \begin{bmatrix} 3 & 4 \end{bmatrix}) + (0.09 \cdot \begin{bmatrix} 6 & 7 \end{bmatrix}) + (0.16 \cdot \begin{bmatrix} 7 & 8 \end{bmatrix}) \\
&= \begin{bmatrix} 0.25 & 0.50 \end{bmatrix} + \begin{bmatrix} 0.18 & 0.27 \end{bmatrix} + \begin{bmatrix} 0.12 & 0.16 \end{bmatrix} + \begin{bmatrix} 0.54 & 0.63 \end{bmatrix} + \begin{bmatrix} 1.12 & 1.28 \end{bmatrix} \\
&= \begin{bmatrix} (0.25 + 0.18 + 0.12 + 0.54 + 1.12) & (0.50 + 0.27 + 0.16 + 0.63 + 1.28) \end{bmatrix} \\
&= \begin{bmatrix} 2.21 & 2.84 \end{bmatrix}
\end{aligned}
$$
* Hitung Penyebut (Denominator): $\sum_{k=1}^{N} (u_{1k})^m$

    Ini adalah penjumlahan semua nilai $(u_{1k})^m$.
$$
\begin{aligned}
\text{Denominator} &= u_{21}^2 + u_{22}^2 + u_{23}^2 + u_{24}^2 + u_{25}^2 \\
&= 0.25 + 0.09 + 0.04 + 0.09 + 0.16 \\
&= 0.63
\end{aligned}
$$


* Hitung Centroid Cluster 2 ($C_1$): $\begin{aligned}\frac{\text{Numerator}}{\text{Denominator}}\end{aligned}$

Terakhir, bagi pembilang dengan penyebut.

$$
\begin{aligned}
C_2 &= \frac{\text{Numerator}}{\text{Denominator}} \\
&= \frac{\begin{bmatrix} 2.21 & 2.84 \end{bmatrix}}{0.63} \\
&= \begin{bmatrix} \frac{2.21}{0.63} & \frac{2.84}{0.63} \end{bmatrix} \\
&\approx \begin{bmatrix} 3.507936508 & 4.507936508 \end{bmatrix}
\end{aligned}
$$


* Hasil Akhir:

Centroid Cluster 2 adalah $\begin{bmatrix} 3.508 & 4.508 \end{bmatrix}$ (dibulatkan hingga tiga angka desimal).



3. **Menghitung serta Memperbarui Nilai Anggota**

Rumus yang digunakan adalah:
$$u_{ji} = \frac{1}{\sum_{k=1}^{C} \left( \frac{\|x_i - c_j\|}{\|x_i - c_k\|} \right)^{2}}$$

Setelah kita mendapatkan nilai centroid untuk semua cluster, maka kita selanjutnya harus memperbarui nilai derajat anggota untuk setiap anggota dengan menggunakan rumus yang sudah penulis berikan di atas serta penulis berikan pada materi rumus



* Perhitungan Derajat Keanggotaan ($u_{ji}$)


Mari kita hitung untuk setiap titik data:

1. Untuk Titik Data $x_1 = [1, 2]$

**Jarak:**
* $\|x_1 - c_1\| = \|[1, 2] - [3.86098655, 4.86098655]\| = \sqrt{(1-3.86098655)^2 + (2-4.86098655)^2} = \sqrt{(-2.86098655)^2 + (-2.86098655)^2} = \sqrt{8.1850125 + 8.1850125} = \sqrt{16.370025} \approx \mathbf{4.045988}$
* $\|x_1 - c_2\| = \|[1, 2] - [3.50793651, 4.50793651]\| = \sqrt{(1-3.50793651)^2 + (2-4.50793651)^2} = \sqrt{(-2.50793651)^2 + (-2.50793651)^2} = \sqrt{6.289748 + 6.289748} = \sqrt{12.579496} \approx \mathbf{3.546758}$

**a. $u_{11}$ (Data $x_1$ ke Klaster $c_1$):**
$u_{11} = \frac{1}{\left( \frac{\|x_1 - c_1\|}{\|x_1 - c_1\|} \right)^2 + \left( \frac{\|x_1 - c_1\|}{\|x_1 - c_2\|} \right)^2}$
$u_{11} = \frac{1}{\left( \frac{4.045988}{4.045988} \right)^2 + \left( \frac{4.045988}{3.546758} \right)^2}$
$u_{11} = \frac{1}{(1)^2 + (1.140816)^2} = \frac{1}{1 + 1.301469} = \frac{1}{2.301469} \approx \mathbf{0.4345}$

**b. $u_{21}$ (Data $x_1$ ke Klaster $c_2$):**
$u_{21} = \frac{1}{\left( \frac{\|x_1 - c_2\|}{\|x_1 - c_1\|} \right)^2 + \left( \frac{\|x_1 - c_2\|}{\|x_1 - c_2\|} \right)^2}$
$u_{21} = \frac{1}{\left( \frac{3.546758}{4.045988} \right)^2 + \left( \frac{3.546758}{3.546758} \right)^2}$
$u_{21} = \frac{1}{(0.87661)^2 + (1)^2} = \frac{1}{0.768449 + 1} = \frac{1}{1.768449} \approx \mathbf{0.5655}$


---
2. Untuk Titik Data $x_2 = [2, 3]$

**Jarak:**
* $\|x_2 - c_1\| = \|[2, 3] - [3.86098655, 4.86098655]\| = \sqrt{(2-3.86098655)^2 + (3-4.86098655)^2} = \sqrt{(-1.86098655)^2 + (-1.86098655)^2} = \sqrt{3.46327 + 3.46327} = \sqrt{6.92654} \approx \mathbf{2.631836}$
* $\|x_2 - c_2\| = \|[2, 3] - [3.50793651, 4.50793651]\| = \sqrt{(2-3.50793651)^2 + (3-4.50793651)^2} = \sqrt{(-1.50793651)^2 + (-1.50793651)^2} = \sqrt{2.27382 + 2.27382} = \sqrt{4.54764} \approx \mathbf{2.132515}$

**a. $u_{12}$ (Data $x_2$ ke Klaster $c_1$):**
$u_{12} = \frac{1}{\left( \frac{2.631836}{2.631836} \right)^2 + \left( \frac{2.631836}{2.132515} \right)^2}$
$u_{12} = \frac{1}{1^2 + (1.23419)^2} = \frac{1}{1 + 1.52312} = \frac{1}{2.52312} \approx \mathbf{0.3963}$

**b. $u_{22}$ (Data $x_2$ ke Klaster $c_2$):**
$u_{22} = \frac{1}{\left( \frac{2.132515}{2.631836} \right)^2 + \left( \frac{2.132515}{2.132515} \right)^2}$
$u_{22} = \frac{1}{(0.81023)^2 + 1^2} = \frac{1}{0.6565 + 1} = \frac{1}{1.6565} \approx \mathbf{0.6037}$


---

3. Untuk Titik Data $x_3 = [3, 4]$

**Jarak:**
* $\|x_3 - c_1\| = \|[3, 4] - [3.86098655, 4.86098655]\| = \sqrt{(3-3.86098655)^2 + (4-4.86098655)^2} = \sqrt{(-0.86098655)^2 + (-0.86098655)^2} = \sqrt{0.7413 + 0.7413} = \sqrt{1.4826} \approx \mathbf{1.217694}$
* $\|x_3 - c_2\| = \|[3, 4] - [3.50793651, 4.50793651]\| = \sqrt{(3-3.50793651)^2 + (4-4.50793651)^2} = \sqrt{(-0.50793651)^2 + (-0.50793651)^2} = \sqrt{0.2579 + 0.2579} = \sqrt{0.5158} \approx \mathbf{0.718192}$

**a. $u_{13}$ (Data $x_3$ ke Klaster $c_1$):**
$u_{13} = \frac{1}{\left( \frac{1.217694}{1.217694} \right)^2 + \left( \frac{1.217694}{0.718192} \right)^2}$
$u_{13} = \frac{1}{1^2 + (1.69549)^2} = \frac{1}{1 + 2.87469} = \frac{1}{3.87469} \approx \mathbf{0.2581}$

**b. $u_{23}$ (Data $x_3$ ke Klaster $c_2$):**
$u_{23} = \frac{1}{\left( \frac{0.718192}{1.217694} \right)^2 + \left( \frac{0.718192}{0.718192} \right)^2}$
$u_{23} = \frac{1}{(0.58983)^2 + 1^2} = \frac{1}{0.3478 + 1} = \frac{1}{1.3478} \approx \mathbf{0.7419}$


---

4. Untuk Titik Data $x_4 = [6, 7]$

**Jarak:**
* $\|x_4 - c_1\| = \|[6, 7] - [3.86098655, 4.86098655]\| = \sqrt{(6-3.86098655)^2 + (7-4.86098655)^2} = \sqrt{(2.13901345)^2 + (2.13901345)^2} = \sqrt{4.57545 + 4.57545} = \sqrt{9.1509} \approx \mathbf{3.025046}$
* $\|x_4 - c_2\| = \|[6, 7] - [3.50793651, 4.50793651]\| = \sqrt{(6-3.50793651)^2 + (7-4.50793651)^2} = \sqrt{(2.49206349)^2 + (2.49206349)^2} = \sqrt{6.2103 + 6.2103} = \sqrt{12.4206} \approx \mathbf{3.524287}$

**a. $u_{14}$ (Data $x_4$ ke Klaster $c_1$):**
$u_{14} = \frac{1}{\left( \frac{3.025046}{3.025046} \right)^2 + \left( \frac{3.025046}{3.524287} \right)^2}$
$u_{14} = \frac{1}{1^2 + (0.85834)^2} = \frac{1}{1 + 0.73675} = \frac{1}{1.73675} \approx \mathbf{0.5758}$

**b. $u_{24}$ (Data $x_4$ ke Klaster $c_2$):**
$u_{24} = \frac{1}{\left( \frac{3.524287}{3.025046} \right)^2 + \left( \frac{3.524287}{3.524287} \right)^2}$
$u_{24} = \frac{1}{(1.16497)^2 + 1^2} = \frac{1}{1.35715 + 1} = \frac{1}{2.35715} \approx \mathbf{0.4242}$


---

5. Untuk Titik Data $x_5 = [7, 8]$

**Jarak:**
* $\|x_5 - c_1\| = \|[7, 8] - [3.86098655, 4.86098655]\| = \sqrt{(7-3.86098655)^2 + (8-4.86098655)^2} = \sqrt{(3.13901345)^2 + (3.13901345)^2} = \sqrt{9.8533 + 9.8533} = \sqrt{19.7066} \approx \mathbf{4.439211}$
* $\|x_5 - c_2\| = \|[7, 8] - [3.50793651, 4.50793651]\| = \sqrt{(7-3.50793651)^2 + (8-4.50793651)^2} = \sqrt{(3.49206349)^2 + (3.49206349)^2} = \sqrt{12.1945 + 12.1945} = \sqrt{24.389} \approx \mathbf{4.938521}$

**a. $u_{15}$ (Data $x_5$ ke Klaster $c_1$):**
$u_{15} = \frac{1}{\left( \frac{4.439211}{4.439211} \right)^2 + \left( \frac{4.439211}{4.938521} \right)^2}$
$u_{15} = \frac{1}{1^2 + (0.89890)^2} = \frac{1}{1 + 0.80802} = \frac{1}{1.80802} \approx \mathbf{0.5531}$

**b. $u_{25}$ (Data $x_5$ ke Klaster $c_2$):**
$u_{25} = \frac{1}{\left( \frac{4.938521}{4.439211} \right)^2 + \left( \frac{4.938521}{4.938521} \right)^2}$
$u_{25} = \frac{1}{(1.11245)^2 + 1^2} = \frac{1}{1.23755 + 1} = \frac{1}{2.23755} \approx \mathbf{0.4469}$



* Memperbarui Nilai Derajat Keanggotaan

| No Data | Nilai Ke C1 | Nilai Ke C2 |
|----------|----------|----------|
| 1 | 0.4345 | 0.5655 |
| 2 | 0.3963 | 0.6037 |
| 3 | 0.2581 | 0.7419 |
| 4 | 0.5758 | 0.4242 |
| 5 | 0.5531 | 0.4469 |



Perhitungan Tersebut Terus diulang sampai dengan mencapai nilai konvergen yang diinginkan

## **Implementasi Fuzzy C-means**

### *Penggunaan Algortima Fuzzy C-Means Pada Contoh data*

Berikut ini adalah implementasi Penggunaan algoritma Fuzzy C-Means Clustering dengan menggunakan python. Data yang digunakan pada code dibawah ini sama dengan data yang sudah penulis hitung sebelumnya. Perbedaannya hanya pada penggunaan bahasa python untuk mendapatkan hasil yang cepat dan juga akurat. Penulis juga menggunakan fungsi objektif serta menghitung konvergensinya agar tidak melakukan iterasi sampai dengan ambang batas maksimal. Sedangkan untuk ambang batas maksimalnya pada code dibawah ini adalah 100 iterasi, akan tetapi karena sudah mencapai batas konvergensinya maka hanya dilakukan 8 iterasi saja.

In [1]:
import numpy as np

# -------------------------------------------
# DATA & PARAMETER
# -------------------------------------------
data = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [6, 7],
    [7, 8]
])

# Inisialisasi keanggotaan awal (baris: cluster, kolom: data)
membership = np.array([
    [0.4345, 0.3963, 0.2582, 0.5758, 0.5531],   # cluster 1
    [0.5655, 0.6037, 0.7418, 0.4242, 0.4469]    # cluster 2
])

m = 2
max_iter = 100
epsilon = 1e-5  # ambang konvergensi


# -------------------------------------------
# FUNGSI UTAMA
# -------------------------------------------
def compute_centroids(data, membership, m):
    um = membership ** m
    return (um @ data) / um.sum(axis=1, keepdims=True)


def update_membership(data, centroids, m):
    n_samples = data.shape[0]
    n_clusters = centroids.shape[0]
    expo = 2.0 / (m - 1.0)
    dist = np.linalg.norm(data[:, None, :] - centroids[None, :, :], axis=2)
    dist = np.where(dist == 0, 1e-10, dist)
    membership = np.empty((n_clusters, n_samples))
    for j in range(n_clusters):
        ratio = (dist[:, j, None] / dist) ** expo
        membership[j, :] = 1.0 / ratio.sum(axis=1)
    return membership


# -------------------------------------------
# ITERASI FCM SAMPAI KONVERGEN
# -------------------------------------------
for iteration in range(max_iter):
    prev_centroids = compute_centroids(data, membership, m)
    membership = update_membership(data, prev_centroids, m)
    new_centroids = compute_centroids(data, membership, m)

    diff = np.linalg.norm(new_centroids - prev_centroids)
    print(f"\nIterasi {iteration+1}")
    for idx, c in enumerate(new_centroids, 1):
        print(f"  Centroid Cluster {idx}: {c}")
    print(f"  Derajat keanggotaan:\n{np.round(membership, 4)}")
    print(f"  Selisih konvergensi: {diff:.6f}")

    if diff < epsilon:
        print(f"\nKonvergen tercapai pada iterasi {iteration+1} dengan selisih {diff:.6f}")
        break
else:
    print("\nMaksimal iterasi tercapai tanpa konvergen.")

final_centroids = new_centroids
final_membership = membership
final_diff = diff




Iterasi 1
  Centroid Cluster 1: [6.00989178 7.00989178]
  Centroid Cluster 2: [2.43824853 3.43824853]
  Derajat keanggotaan:
[[0.2728 0.177  0.0164 0.8    0.7147]
 [0.7272 0.823  0.9836 0.2    0.2853]]
  Selisih konvergensi: 2.266857

Iterasi 2
  Centroid Cluster 1: [6.45808038 7.45808038]
  Centroid Cluster 2: [2.03269005 3.03269005]
  Derajat keanggotaan:
[[0.0761 0.0118 0.0337 1.     0.955 ]
 [0.9239 0.9882 0.9663 0.     0.045 ]]
  Selisih konvergensi: 0.854811

Iterasi 3
  Centroid Cluster 1: [6.48792812 7.48792812]
  Centroid Cluster 2: [1.97473224 2.97473224]
  Derajat keanggotaan:
[[3.460e-02 1.000e-04 7.260e-02 9.868e-01 9.882e-01]
 [9.654e-01 9.999e-01 9.274e-01 1.320e-02 1.180e-02]]
  Selisih konvergensi: 0.092195

Iterasi 4
  Centroid Cluster 1: [6.48818659 7.48818659]
  Centroid Cluster 2: [1.96729962 2.96729962]
  Derajat keanggotaan:
[[0.0306 0.     0.0795 0.9855 0.9897]
 [0.9694 1.     0.9205 0.0145 0.0103]]
  Selisih konvergensi: 0.010518

Iterasi 5
  Centroid Cluster 

### *Penggunaan Algoritma Fuzzy C-Means Pada Data Iris*

In [2]:
# Import library
import pymysql
import psycopg2
from sqlalchemy import create_engine
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import numpy as np
import base64
import os
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [3]:
# Mengkoneksi database dengan python

# for mysql
timeout = 10
connection = pymysql.connect(
    charset="utf8mb4",
    connect_timeout=timeout,
    cursorclass=pymysql.cursors.DictCursor,
    db="defaultdb",
    host="mysql-726cd75-mysqlpendata-11.h.aivencloud.com",
    password="AVNS_LHA80D-LNsKI6wncjfc",
    read_timeout=timeout,
    port=20734,
    user="avnadmin",
    write_timeout=timeout,
)
mysql_engine = create_engine("mysql+pymysql://avnadmin:AVNS_LHA80D-LNsKI6wncjfc@mysql-726cd75-mysqlpendata-11.h.aivencloud.com:20734/defaultdb")



# for postgre
def main():
    conn = psycopg2.connect('postgres://avnadmin:AVNS__Y6I8K0T7rSnwnRgE1U@pg-3266d3cf-postgresqlpendata-11.h.aivencloud.com:20817/defaultdb?sslmode=require')

    query_sql = 'SELECT VERSION()'

    cur = conn.cursor()
    cur.execute(query_sql)

    version = cur.fetchone()[0]
    print(version)

if __name__ == "__main__":
    main()
postgres_engine = create_engine("postgresql+psycopg2://avnadmin:AVNS__Y6I8K0T7rSnwnRgE1U@pg-3266d3cf-postgresqlpendata-11.h.aivencloud.com:20817/defaultdb")




PostgreSQL 16.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3), 64-bit


In [4]:
# Ambil data dari MySQL
mysql_query = "SELECT * FROM iris_data"
mysql_df = pd.read_sql(mysql_query, mysql_engine)

# Ambil data dari PostgreSQL
pg_query = 'SELECT * FROM postgre'
pg_df = pd.read_sql(pg_query, postgres_engine)

# Gabungkan kedua databases
merge_df = pd.merge(mysql_df, pg_df, left_on="id", right_on='id', how='outer')

In [5]:
# Menampilkan data yang diambil database dan ditampilkan dalam bentuk tabel
selected_columns = ["id", "class", "petal_length", "petal_width", "sepal length", "sepal width"]  
filtered_df = merge_df[selected_columns]

print("Berikut ini adalah tampilan data yang diambil dari database :")
print()
print(filtered_df)


Berikut ini adalah tampilan data yang diambil dari database :

      id           class  petal_length  petal_width  sepal length  sepal width
0      1     Iris-setosa          86.4         70.0          20.1         30.5
1      2     Iris-setosa           1.4          0.2           4.9          3.0
2      3     Iris-setosa           1.3          0.2           4.7          3.2
3      4     Iris-setosa           1.5          0.2           4.6          3.1
4      5     Iris-setosa           1.4          0.2           5.0          3.6
..   ...             ...           ...          ...           ...          ...
145  146  Iris-virginica           5.2          2.3           6.7          3.0
146  147  Iris-virginica           5.0          1.9           6.3          2.5
147  148  Iris-virginica           5.2          2.0           6.5          3.0
148  149  Iris-virginica           5.4          2.3           6.2          3.4
149  150  Iris-virginica           5.1          1.8           5.9   

In [6]:
# Mengubah dataset 
filtered_df.loc[filtered_df['id'] == 1, 'petal_length'] = 1.4
filtered_df.loc[filtered_df['id'] == 1, 'petal_width'] = 0.2
filtered_df.loc[filtered_df['id'] == 1, 'sepal length'] = 5.1
filtered_df.loc[filtered_df['id'] == 1, 'sepal width'] = 3.5

In [7]:
normal_iris = filtered_df.copy()
print(normal_iris)

      id           class  petal_length  petal_width  sepal length  sepal width
0      1     Iris-setosa           1.4          0.2           5.1          3.5
1      2     Iris-setosa           1.4          0.2           4.9          3.0
2      3     Iris-setosa           1.3          0.2           4.7          3.2
3      4     Iris-setosa           1.5          0.2           4.6          3.1
4      5     Iris-setosa           1.4          0.2           5.0          3.6
..   ...             ...           ...          ...           ...          ...
145  146  Iris-virginica           5.2          2.3           6.7          3.0
146  147  Iris-virginica           5.0          1.9           6.3          2.5
147  148  Iris-virginica           5.2          2.0           6.5          3.0
148  149  Iris-virginica           5.4          2.3           6.2          3.4
149  150  Iris-virginica           5.1          1.8           5.9          3.0

[150 rows x 6 columns]


In [8]:
data_column = ['petal_length', 'petal_width', 'sepal length', 'sepal width']
data_selected = normal_iris[data_column]

In [9]:
# Normalisasi data
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data_selected)

In [10]:
def initialize_membership(n_samples, n_clusters):
    u = np.random.dirichlet(np.ones(n_clusters), size=n_samples)
    return u.T  # bentuk: (n_clusters, n_samples)

def compute_centroids(data, u, m):
    um = u ** m
    return (um @ data) / um.sum(axis=1)[:, None]

def update_membership(data, centroids, m):
    dist = np.linalg.norm(data[:, None, :] - centroids[None, :, :], axis=2) + 1e-10
    exp = 2 / (m - 1)
    temp = (dist[:, :, None] / dist[:, None, :]) ** exp
    u_new = 1 / temp.sum(axis=2)
    return u_new.T


In [11]:
def fuzzy_c_means(data, n_clusters=3, m=2, max_iter=100, epsilon=1e-5):
    n_samples = data.shape[0]
    u = initialize_membership(n_samples, n_clusters)
    
    for i in range(max_iter):
        centroids = compute_centroids(data, u, m)
        u_new = update_membership(data, centroids, m)

        if np.linalg.norm(u_new - u) < epsilon:
            print(f"Konvergen pada iterasi ke-{i+1}")
            break
        u = u_new

        print(f"Iterasi {i+1} - Centroid:")
        for idx, c in enumerate(centroids):
            print(f"  Cluster {idx+1}: {c}")

    return centroids, u


In [12]:
centroids, membership = fuzzy_c_means(data_scaled, n_clusters=3)

Iterasi 1 - Centroid:
  Cluster 1: [0.44467107 0.42700184 0.4144863  0.41264519]
  Cluster 2: [0.49162695 0.49699399 0.42929206 0.44320483]
  Cluster 3: [0.45190976 0.44052456 0.42600109 0.46340754]
Iterasi 2 - Centroid:
  Cluster 1: [0.41828169 0.40320826 0.39144383 0.43316328]
  Cluster 2: [0.54283382 0.53683205 0.47258995 0.42246294]
  Cluster 3: [0.42704792 0.41780515 0.41165215 0.46463873]
Iterasi 3 - Centroid:
  Cluster 1: [0.33189564 0.31713177 0.33537784 0.46347497]
  Cluster 2: [0.61721653 0.60988    0.52543171 0.40100053]
  Cluster 3: [0.3523352  0.34066729 0.35898091 0.47984064]
Iterasi 4 - Centroid:
  Cluster 1: [0.20750113 0.18862532 0.25681644 0.50626075]
  Cluster 2: [0.67725429 0.67591298 0.5703336  0.39098138]
  Cluster 3: [0.25085776 0.23246391 0.28550899 0.49663689]
Iterasi 5 - Centroid:
  Cluster 1: [0.13491219 0.11483622 0.21681017 0.5421671 ]
  Cluster 2: [0.69808129 0.70207516 0.58698315 0.39041138]
  Cluster 3: [0.22438289 0.2027163  0.26075574 0.49036501]
Itera

In [13]:
centroids_original_scale = scaler.inverse_transform(centroids)

In [14]:
# Membuat DataFrame hasil
df_result = pd.DataFrame(normal_iris, columns=['petal_length', 'petal_width', 'sepal length', 'sepal width'])
for i in range(membership.shape[0]):
    df_result[f'Cluster_{i+1}_Membership'] = membership[i]

print(df_result.head())


   petal_length  petal_width  sepal length  sepal width  Cluster_1_Membership  \
0           1.4          0.2           5.1          3.5              0.992968   
1           1.4          0.2           4.9          3.0              0.931252   
2           1.3          0.2           4.7          3.2              0.965978   
3           1.5          0.2           4.6          3.1              0.937062   
4           1.4          0.2           5.0          3.6              0.983855   

   Cluster_2_Membership  Cluster_3_Membership  
0              0.002264              0.004767  
1              0.020409              0.048338  
2              0.010542              0.023480  
3              0.019060              0.043878  
4              0.005307              0.010838  
